RailsTesting/blog/config/routes.rb
Blog::Application.routes.draw do
  namespace :api, :defaults => {:format => "json"} do
    api_version(:module => "V1", :path => {:value => "v1"}, default: true) do
      resources :articles
    end
  end
  root 'articles#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  resources :articles
  resources :users
  resources :sessions
end

RailsTesting/blog/app/models/article.rb
class Article < ActiveRecord::Base
	attr_accessor :name
end

RailsTesting/blog/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password, :password_confirmation
  before_save :encrypt_password
  require 'bcrypt'
  
  # def self.authenticate(email, password)
  #   user = find_by_email(email)
  #   if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  #     user
  #   else
  #     nil
  #   end
  # end

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  private

    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
end

RailsTesting/blog/app/controllers/api/v1/articles_controller.rb
# Controller for Article
class Api::V1::ArticlesController < ApplicationController
  # include ActionController::MimeResponds
  include ActionController::ImplicitRender
  
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to action: :index
  end

  def show
    @article = Article.find params[:id]
  end

  private

    def article_params
      params.require(:article).permit(:title, :content)
    end
end

RailsTesting/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

RailsTesting/blog/app/controllers/articles_controller.rb
# Controller for Article
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to action: :index
  end

  def show
    @article = Article.find params[:id]
  end

  private

    def article_params
      params.require(:article).permit(:title, :content)
    end
end

RailsTesting/blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now.alert = 'Invalid username or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url # :notice => "Logged out!"
  end
end

RailsTesting/blog/app/controllers/users_controller.rb
###
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user)
        .permit(:id, :username, :password, :password_confirmation)
    end
end

RailsTesting/blog/app/helpers/sessions_helper.rb
module SessionsHelper
end

RailsTesting/blog/app/helpers/users_helper.rb
module UsersHelper
end

RailsTesting/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
	  <% if current_user %>
	    Logged in as <%= current_user.username %>.
	    <%= link_to "Log out", logout_path %>
	  <% else %>
	    <%= link_to "Sign up", signup_path %> or
	    <%= link_to "log in", login_path %>
	  <% end %>
	</div>

	<% flash.each do |name, msg| %>
	  <%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>

<%= yield %>

</body>
</html>

RailsTesting/blog/app/views/users/index.html.erb
<% @users.each do |user| %>
	<%= user.username %>
<% end %>

RailsTesting/blog/app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<p>
		<%= f.label :username %>
		<%= f.text_field :username %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.text_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation, "Retype Password" %>
		<%= f.text_field :password_confirmation %>
	</p>
	<%= f.submit "Sign Up" %>
<% end %>

RailsTesting/blog/app/views/users/show.html.erb
<h1>User Info</h1>
<p>
	<%= @user.username %>
</p>

<% if current_user && current_user.admin? || current_user == @user %>
    <%= link_to "Edit Profile", edit_user_path(@user) %>
<% end %>